### ISSUE TITLE
ESNext and CommonJS issue

### ISSUE THREAD

**Issue by allenhdev** [synapsecns/sdk#101]
My project uses commonJS but this sdk is ESNext. I am getting the following error:

```
...
const sdk_1 = require("@synapseprotocol/sdk");

Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/my_project/node_modules/@synapseprotocol/sdk/dist/index.js from /path/to/my_project/dist/src/bridges/synapse/utils/chainUtils.js not supported.
Instead change the require of index.js in /path/to/my_project/dist/path/to/code/file.js to a dynamic import() which is available in all CommonJS modules.
```

NOTE: I use nestjs 8.0.0, typescript 4.3.5

Any suggestions on this issue?

**Comment by bleaker0x** [comment]
I've seen this issue come up with NestJS before. While I do hope to-- at some point in the future -- support CommonJS for the few build systems which still require it, it's proven to be more than a simple configuration switch/setup due to the project's structure and reliance on modern NodeJS and Typescript features. 

One thing which _might_ work for you is to pass either or both of the following flags (as `node-options`) to your build system:

- `--es-module-specifier-resolution=node`
- `--loader=ts-node/esm` (this requires having [ts-node](https://github.com/TypeStrong/ts-node) installed as a `devDependency`)
